### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by billyrudi** [tiagordc/node-red-contrib-tcp-server#1]
i'm happy to send you a working project that i have develop..

[Archivio.zip](https://github.com/tiagordc/node-red-contrib-tcp-server/files/3767545/Archivio.zip)

**Comment by tiagordc** [comment]
thanks, will try to leverage these features on the new node

**Comment by tiagordc** [comment]
Can you have a look at v0.1.0? 

When closing or writing you can define to which address you want to do that action.

**Comment by tiagordc** [comment]
Let me know if this is not working for you.

**Comment by billyrudi** [comment]
Hi, tiago
i will try as soon as. tanks
can you send one example?
